### ISSUE TITLE
Service Worker Error

### ISSUE THREAD

**Issue by pdw207** [ooade/NextSimpleStarter#12]
Two errors relating to service worker. Can you also explain the service worker in more detail?

Error: ENOENT: no such file or directory, stat '/Users/paulwilson/vermonster/opensource/resistance-calendar/.next/sw.js'

Uncaught (in promise) TypeError: Request scheme 'chrome-extension' is unsupported
    at sw.js:formatted:279
<img width="1035" alt="screen shot 2017-02-24 at 3 02 41 pm" src="https://cloud.githubusercontent.com/assets/4714249/23318895/524ebdbc-faa2-11e6-99f1-fd9a5fea44d2.png">

**Comment by ooade** [comment]
NextSS don't have a service worker file per say. We're making use of [sw-precache-webpack-plugin](https://github.com/goldhand/sw-precache-webpack-plugin) which inherently depends on [sw-precache](https://github.com/GoogleChrome/sw-precache). All i did was just to set the rule the service worker will follow [here](https://github.com/ooade/NextSimpleStarter/blob/master/next.config.js) and sw-precache took it from there by generating a sw.js file based on the proposed rules. 

If you're having a `ENOENT` error, it would seem that the sw isn't built or you tried using it on dev environment, which i disabled.

The `Request scheme 'chrome-extension' is unsupported` is not from NextSS, like i said earlier, we don't handle service workers. But, the issue is related to https://github.com/GoogleChrome/sw-toolbox/issues/171 
The service worker tries to cache everything it sees without the exception of chrome extensions or so... that's why we have that error coming up.
cc @goldhand

**Comment by goldhand** [comment]
@ooade is correct to disable this during development.

So it seems the application is trying to cache a chrome extension that a user has installed.
Does disabling all chrome extensions remove this error?

I think it is https://github.com/ooade/NextSimpleStarter/blob/aba3f7f8611f5ab7809e67e24d3d16531eab9bd5/next.config.js#L24 that is caching the chrome-extensions. Not sure what else in the config would cause that.

**Comment by ooade** [comment]
@goldhand Yeah disabling all chrome extensions removes the error. 
P.S: You're probably right about that line.

@pdw207 Will you like to fix this?

**Comment by pdw207** [comment]
Does Next's `prefetch` link attribute also preload assets?  I think you may be correct about the `Request scheme 'chrome-extension' is unsupported`

**Comment by ooade** [comment]
No. It downloads just JS code https://github.com/zeit/next.js#prefetching-pages

**Comment by ooade** [comment]
And thanks for raising the issue. I've pushed the fix to https://nextss.now.sh
