### ISSUE TITLE
[FEATURE] : Add support for Tailwind CSS also

### ISSUE THREAD

**Issue by Manjit2003** [ooade/NextSimpleStarter#173]
It would be a great if this awesome template also had support for Tailwind css.

**Comment by ooade** [comment]
Adding support for Tailwind is more like forking the template and building one for tailwind or completely removing MUI and adding Tailwind 😅

Rather than doing any of those, we'd definitely make it more low level, that is, not using any CSS library. That way makes it easier to maintain and I don't have to worry much about the CSS library as this repo is more targeted towards the Nextjs side of things.
