### ISSUE TITLE
Is it possible to use SWPrecacheWebpackPlugin to make a service worker from some chosen pages?

### ISSUE THREAD

**Issue by iamsoorena** [ooade/NextSimpleStarter#46]
I would love to know how you would approach this problem.
for example when you have 3 pages:
page1
page2
page3
and you only want service worker to include page1.

**Comment by MacKentoch** [comment]
@iamsoorena I use another approach for PWA with Next.

1- I use a Layout component (rather than _document) that registers my service worker in each page.
So I could register on specific pages by passing a prop for example.

2- I user my own server implementation to serve ./sw.js so that I don't need webpack at all.

My version: [react-redux-nextjs-bootstrap-pwa-starter](https://github.com/MacKentoch/react-redux-nextjs-bootstrap-pwa-starter).

This approach is different (does not mean it is better or worse). 
It emphasis there are many way to reach the same objective: that is nice.

**Comment by ooade** [comment]
@MacKentoch Maybe you need to update your fork. We ditched using _document a long time ago, had some issues with that approach. We now **automagically** add it to a webpack chunk _main.js_ so it registers on every page. 
* Your layout approach will definitely work and I'm also suggesting it to you @iamsoorena 
---
Sorry for the late response.
